language: csharp
mono: none
dotnet: 2.1.502
solution: smartsheet-csharp-sdk-v2.sln

before_install:
  - git clone https://github.com/smartsheet-platform/smartsheet-sdk-tests.git
  - smartsheet-sdk-tests/travis_scripts/install_wiremock.sh

script:
  - find * -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild -v 2.5.1
  - dotnet build smartsheet-csharp-sdk-v2.csproj -f netstandard2.0
  - dotnet test IntegrationTestSDK/netcoreapp2.0/integration-test-sdk-netcoreapp20.csproj /p:CollectCoverage=true
  - smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
  - dotnet test TestSDKMockAPI/netcoreapp2.0/mock-api-test-sdk-netcoreapp20.csproj /p:CollectCoverage=true /p:MergeWith="./coverage.json" /p:CoverletOutputFormat=opencover
  # renaming the old .csproj to avoid https://github.com/dotnet/cli/issues/9738 
  - mv Smartsheet-csharp-sdk.csproj Smartsheet-csharp-sdk.csproj.1
  - dotnet tool install -g coveralls.net --version 1.0.0 
  - csmacnz.Coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

